### ISSUE TITLE
ModuleNotFoundError: No module named 'FreeCAD'

### ISSUE THREAD

**Issue by bullestock** [cqparts/cqparts#165]
Python 3.10.4

cqparts installed via pip (0.2.1)

```
Python 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cqparts.params import ParametricObject, Float, Int
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/torsten/.local/lib/python3.10/site-packages/cqparts/__init__.py", line 77, in <module>
    from .component import Component
  File "/home/torsten/.local/lib/python3.10/site-packages/cqparts/component.py", line 2, in <module>
    from .constraint import Mate
  File "/home/torsten/.local/lib/python3.10/site-packages/cqparts/constraint/__init__.py", line 12, in <module>
    from .mate import Mate
  File "/home/torsten/.local/lib/python3.10/site-packages/cqparts/constraint/mate.py", line 3, in <module>
    from ..utils.geometry import CoordSystem
  File "/home/torsten/.local/lib/python3.10/site-packages/cqparts/utils/__init__.py", line 18, in <module>
    from .geometry import CoordSystem
  File "/home/torsten/.local/lib/python3.10/site-packages/cqparts/utils/geometry.py", line 6, in <module>
    import FreeCAD
ModuleNotFoundError: No module named 'FreeCAD'

```

**Comment by g-simmons** [comment]
Same here

**Comment by Spoutnik97** [comment]
me too
